@startuml
class Handler {
    mQueue : MessageQueue
    mLooper : Looper
    mCallBack : CallBack

    void method()
}

class Looper {
    {static} sThreadLocal : ThreadLocal<Looper>
    mQueue : MessageQueue

    {static} void myLooper()
    {static} void prepare()
    {static} void loop()
}

class MessageQueue {
    boolean enqueueMessage(Message msg,long when)
    Message next()
}



Handler *- Looper
Handler *- MessageQueue



@enduml